# Path where the mp3 files are located

path: '/Users/javier/Desktop/mp3'
path_recursive : '/Users/javier/Desktop/mp3/**/*.mp3'
path_popularity:

#API and Project id for Google Images API

# Google Images API
api_google_images : 'api_google_images'
cx_id_google_images : 'cx_id_google_images'

#Discogs
token_discogs : 'token_discogs'

#Musicbrainz
user_musicbrainz : 'user_musicbrainz'
password_musicbrainz : 'password_musicbrainz'

#Spotify
spotify_client_id : 'spotify_client_id'
spotify_secret : 'spotify_secret'

#Genius
token_genius : 'token_genius'


# LastFM
last_fm_api_key : "last_fm_api_key"
last_fm_api_secret : "last_fm_api_secret"


save_path_local_concerts: '/Users/javier/IdeaProjects/vonfreiren.github.io/_concerts'
save_path_local_popularity: '/Users/javier/IdeaProjects/vonfreiren.github.io/_includes/popularity.html'